name: SwiftLint

on:
  pull_request:
    paths:
      - '**/*.swift'
  push:
    paths:
      - '**/*.swift'

jobs:
  lint:
    name: Run SwiftLint
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          echo "Installing Homebrew..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || true

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

