opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - force_try
  - joined_default_parameter
  - trailing_closure
  - vertical_whitespace_between_cases

included:
  - MenuTaroApp

excluded:
  - Pods
  - Carthage
  - DerivedData

line_length:
  warning: 120
  error: 160

type_body_length:
  warning: 200
  error: 300

function_body_length:
  warning: 40
  error: 80

identifier_name:
  excluded:
    - id
    - URL
